
package sk.hlad.velky.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecipesService", targetNamespace = "http://soap.velky.hlad.sk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecipesService {


    /**
     * 
     * @param arg0
     * @return
     *     returns sk.hlad.velky.soap.Recipe
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipe", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetRecipe")
    @ResponseWrapper(localName = "getRecipeResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetRecipeResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/getRecipeRequest", output = "http://soap.velky.hlad.sk/RecipesService/getRecipeResponse")
    public Recipe getRecipe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecipe", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.EditRecipe")
    @ResponseWrapper(localName = "editRecipeResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.EditRecipeResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/editRecipeRequest", output = "http://soap.velky.hlad.sk/RecipesService/editRecipeResponse")
    public int editRecipe(
        @WebParam(name = "arg0", targetNamespace = "")
        Recipe arg0);

    /**
     * 
     * @return
     *     returns java.util.List<sk.hlad.velky.soap.Recipe>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRecipes", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetAllRecipes")
    @ResponseWrapper(localName = "getAllRecipesResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetAllRecipesResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/getAllRecipesRequest", output = "http://soap.velky.hlad.sk/RecipesService/getAllRecipesResponse")
    public List<Recipe> getAllRecipes();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<sk.hlad.velky.soap.Recipe>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipesByIng", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetRecipesByIng")
    @ResponseWrapper(localName = "getRecipesByIngResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetRecipesByIngResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/getRecipesByIngRequest", output = "http://soap.velky.hlad.sk/RecipesService/getRecipesByIngResponse")
    public List<Recipe> getRecipesByIng(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRecipe", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.DeleteRecipe")
    @ResponseWrapper(localName = "deleteRecipeResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.DeleteRecipeResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/deleteRecipeRequest", output = "http://soap.velky.hlad.sk/RecipesService/deleteRecipeResponse")
    public boolean deleteRecipe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRecipe", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.AddRecipe")
    @ResponseWrapper(localName = "addRecipeResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.AddRecipeResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/addRecipeRequest", output = "http://soap.velky.hlad.sk/RecipesService/addRecipeResponse")
    public int addRecipe(
        @WebParam(name = "arg0", targetNamespace = "")
        Recipe arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<sk.hlad.velky.soap.Recipe>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipesByKeyWord", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetRecipesByKeyWord")
    @ResponseWrapper(localName = "getRecipesByKeyWordResponse", targetNamespace = "http://soap.velky.hlad.sk/", className = "sk.hlad.velky.soap.GetRecipesByKeyWordResponse")
    @Action(input = "http://soap.velky.hlad.sk/RecipesService/getRecipesByKeyWordRequest", output = "http://soap.velky.hlad.sk/RecipesService/getRecipesByKeyWordResponse")
    public List<Recipe> getRecipesByKeyWord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
