
package sk.hlad.velky.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecipesServiceService", targetNamespace = "http://soap.velky.hlad.sk/", wsdlLocation = "http://localhost:8888/recipes?wsdl")
public class RecipesServiceService
    extends Service
{

    private final static URL RECIPESSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException RECIPESSERVICESERVICE_EXCEPTION;
    private final static QName RECIPESSERVICESERVICE_QNAME = new QName("http://soap.velky.hlad.sk/", "RecipesServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/recipes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECIPESSERVICESERVICE_WSDL_LOCATION = url;
        RECIPESSERVICESERVICE_EXCEPTION = e;
    }

    public RecipesServiceService() {
        super(__getWsdlLocation(), RECIPESSERVICESERVICE_QNAME);
    }

    public RecipesServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECIPESSERVICESERVICE_QNAME, features);
    }

    public RecipesServiceService(URL wsdlLocation) {
        super(wsdlLocation, RECIPESSERVICESERVICE_QNAME);
    }

    public RecipesServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECIPESSERVICESERVICE_QNAME, features);
    }

    public RecipesServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecipesServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecipesService
     */
    @WebEndpoint(name = "RecipesServicePort")
    public RecipesService getRecipesServicePort() {
        return super.getPort(new QName("http://soap.velky.hlad.sk/", "RecipesServicePort"), RecipesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecipesService
     */
    @WebEndpoint(name = "RecipesServicePort")
    public RecipesService getRecipesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.velky.hlad.sk/", "RecipesServicePort"), RecipesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECIPESSERVICESERVICE_EXCEPTION!= null) {
            throw RECIPESSERVICESERVICE_EXCEPTION;
        }
        return RECIPESSERVICESERVICE_WSDL_LOCATION;
    }

}
